apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: daemonset-e2e.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: multi-networkpolicy-ds-amd64
      namespace: kube-system
