# This dockerfile is specific to building Multus for OpenShift
FROM golang:1.25.11 AS build

# Add everything
ADD . /usr/src/multi-networkpolicy-nftables
WORKDIR /usr/src/multi-networkpolicy-nftables
RUN CGO_ENABLED=0 go build ./cmd/multi-networkpolicy-nftables/

FROM registry.access.redhat.com/ubi8/ubi:latest
LABEL org.opencontainers.image.source="https://github.com/k8snetworkplumbingwg/multi-networkpolicy-nftables"
RUN dnf install -y nftables
COPY --from=build /usr/src/multi-networkpolicy-nftables/multi-networkpolicy-nftables /usr/bin
WORKDIR /usr/bin

LABEL io.k8s.display-name="Multus NetworkPolicy" \
      io.k8s.description="This is a component of OpenShift Container Platform and provides NetworkPolicy objects for secondary interfaces created with Multus CNI" \
      io.openshift.tags="openshift" \
      maintainer="Doug Smith <dosmith@redhat.com>"

ENTRYPOINT ["multi-networkpolicy-nftables"]
