apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-networkpolicy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-networkpolicy
rules:
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - multi-networkpolicies
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-networkpolicy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-networkpolicy
subjects:
- kind: ServiceAccount
  name: multi-networkpolicy
  namespace: kube-system
---
apiVersion: v1
data:
  custom-v4-rules.txt: |
    # accept redirect
    -p icmp --icmp-type redirect -j ACCEPT
    # accept fragmentation-needed (for MTU discovery)
    -p icmp --icmp-type fragmentation-needed -j ACCEPT
kind: ConfigMap
metadata:
  labels:
    app: multi-networkpolicy
    tier: node
  name: multi-networkpolicy-custom-v4-rules
  namespace: kube-system
---
apiVersion: v1
data:
  custom-v6-rules.txt: |
    # accept NDP
    -p icmpv6 --icmpv6-type neighbor-solicitation -j ACCEPT
    -p icmpv6 --icmpv6-type neighbor-advertisement -j ACCEPT
    # accept RA/RS
    -p icmpv6 --icmpv6-type router-solicitation -j ACCEPT
    -p icmpv6 --icmpv6-type router-advertisement -j ACCEPT
    # accept redirect
    -p icmpv6 --icmpv6-type redirect -j ACCEPT
    # accept packet-too-big (for MTU discovery)
    -p icmpv6 --icmpv6-type packet-too-big -j ACCEPT
kind: ConfigMap
metadata:
  labels:
    app: multi-networkpolicy
    tier: node
  name: multi-networkpolicy-custom-v6-rules
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: multi-networkpolicy
    name: multi-networkpolicy
    tier: node
  name: multi-networkpolicy-ds-amd64
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: multi-networkpolicy
  template:
    metadata:
      labels:
        app: multi-networkpolicy
        name: multi-networkpolicy
        tier: node
    spec:
      containers:
      - args:
        - --host-prefix=/host
        - --pod-iptables=/var/lib/multi-networkpolicy
        - --container-runtime-endpoint=/run/containerd/containerd.sock
        - --sync-period=1
        - --network-plugins=macvlan,bond,ipvlan
        - -v=10
        command:
        - /usr/bin/multi-networkpolicy-nftables
        image: localhost:5000/multi-networkpolicy-nftables:e2e
        imagePullPolicy: IfNotPresent
        name: multi-networkpolicy
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 80Mi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host
          readOnly: true
        - mountPath: /var/lib/multi-networkpolicy
          name: var-lib-multinetworkpolicy
        - mountPath: /etc/multi-networkpolicy/rules
          name: multi-networkpolicy-custom-rules
          readOnly: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: multi-networkpolicy
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /
        name: host
      - hostPath:
          path: /var/lib/multi-networkpolicy
        name: var-lib-multinetworkpolicy
      - name: multi-networkpolicy-custom-rules
        projected:
          sources:
          - configMap:
              name: multi-networkpolicy-custom-v4-rules
          - configMap:
              name: multi-networkpolicy-custom-v6-rules
  updateStrategy:
    type: RollingUpdate
